# Generated by Django 3.0.3 on 2020-04-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_additem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='itemType',
            field=models.CharField(default='essential', max_length=50),
            preserve_default=False,
        ),
    ]
