# Generated by Django 3.0.3 on 2020-04-25 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0003_additem_itemtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additem',
            old_name='date',
            new_name='dateAdded',
        ),
        migrations.AddField(
            model_name='additem',
            name='dateDisplayed',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='additem',
            name='itemType',
            field=models.CharField(max_length=10),
        ),
    ]
