# Generated by Django 3.1.2 on 2020-11-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20201012_1023'),
        ('budget', '0002_auto_20201007_0934'),
    ]

    operations = [
    ]
