# Generated by Django 3.1.2 on 2020-11-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_merge_20201104_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedexpenses',
            name='itemDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='availableCash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='summary',
            name='monthlySavings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
