# Generated by Django 3.0.3 on 2020-11-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20201108_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='actualCash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
