# Generated by Django 3.0.3 on 2020-11-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_summary_actualcash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='itemDate',
            field=models.DateTimeField(),
        ),
    ]
